### ISSUE TITLE
[Feature]: Enable User to Ignore the Prerequisites in "tooth.json" at Their Own Risk

### ISSUE THREAD

**Issue by RainoutOvO** [futrime/lip#122]
### Is your feature request related to a problem? Please describe.

Sometimes, the original developer of the plugin may be too busy to update, but the plugin are sometimes self-adaptable (e.g. js).

### Describe the solution you'd like

Enable users to ignore the prerequisites at their own risk by using an additional label in the command when installing.
E.g. `lip install github.com/LiteLDev/LegacyMoney@0.3.0 -i`

### Additional context

It is important to ensure that this function is made **not** simple for users to operate, such as just inputting "y" during the installation process. This can lead to serious issues for inexperienced operators who may overlook the warnings, for it is important to note that the function may not be applicable in all situations.

**Comment by futrime** [comment]
Try `--no-dependencies` flag.
