### ISSUE TITLE
[Bug]: 卸载可执行文件时乱码

### ISSUE THREAD

**Issue by Litezero** [futrime/lip#137]
### Describe the bug

![image](https://github.com/lippkg/lip/assets/114818763/c4ddf0b4-b3ac-4b09-b364-338f169f487e)
卸载可执行文件时会遇到此乱码

### To Reproduce

只需卸载可执行文件

### Expected behavior

乱码得到修复，显示为正确内容

### Platform

Windows10 Arm64

### Version

0.22.0

**Comment by PA733** [comment]
收到，请问系统是否有开启“强制 unicode” 功能？

**Comment by PA733** [comment]
无足够信息，目前无法复现。
