### ISSUE TITLE
[Bug]: lip -h中存在错误数目的缩进

### ISSUE THREAD

**Issue by odorajbotoj** [futrime/lip#138]
### Describe the bug

`lip -h` 中 `Commands` 项 `config` 子项缩进有误，导致排版不美观。

### To Reproduce

`lip -h`

### Expected behavior

`lip -h` 中 `Commands` 项 `config` 子项与其他子项缩进统一。

### Screenshots

<img width="507" alt="image" src="https://github.com/lippkg/lip/assets/42602346/5abdd85f-cbf1-4b09-8f86-f5073ee7af6a">

### Version

0.22.0

**Comment by ShrBox** [comment]
- [ ]
